export * from './button'
// export * from './calendar'
export * from './card'
export * from './checkbox'
export * from './form'
export * from './icon'
export * from './input'
export * from './progress'
export * from './select'
export * from './switch'
export * from './upload'
export * from './tooltip'
export * from './tree'
export * from './virtual-list'

// 此处声明全局注册函数