name: Deploy Docs

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install pnpm and dependences
        uses: pnpm/action-setup@v2
        with:
          version: 10.7.1 # pnpm，但是它只在当前步骤可用，后续步骤没继承它的环境,所以要添加PATH
          run_install: true
      

      # - name: Test with vitest
      #  run: npm run test

      - name: Build project
        run: pnpm run build

      - name: Update version
        run: npx changeset version

      - name: Login to npm
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Publish new npm package
        run: npx changeset publish
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

